// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt7NNpUhx-g4gBMTdy3Wo0GUcxFXb9QRQ',
    appId: '1:657087009134:web:1b5e3f5cb4c4265c5bf17f',
    messagingSenderId: '657087009134',
    projectId: 'bybv-69690',
    authDomain: 'bybv-69690.firebaseapp.com',
    storageBucket: 'bybv-69690.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe_0Yi22AnYWPGlsKot-fIkeF7PFZS6AA',
    appId: '1:657087009134:android:69cbc21314f0f48c5bf17f',
    messagingSenderId: '657087009134',
    projectId: 'bybv-69690',
    storageBucket: 'bybv-69690.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDWXI2DE49BfXvlvI0Uz1T1KMIwMnblwE',
    appId: '1:657087009134:ios:bca42d04b1db9b2e5bf17f',
    messagingSenderId: '657087009134',
    projectId: 'bybv-69690',
    storageBucket: 'bybv-69690.firebasestorage.app',
    iosBundleId: 'com.example.bybv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDWXI2DE49BfXvlvI0Uz1T1KMIwMnblwE',
    appId: '1:657087009134:ios:bca42d04b1db9b2e5bf17f',
    messagingSenderId: '657087009134',
    projectId: 'bybv-69690',
    storageBucket: 'bybv-69690.firebasestorage.app',
    iosBundleId: 'com.example.bybv',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBt7NNpUhx-g4gBMTdy3Wo0GUcxFXb9QRQ',
    appId: '1:657087009134:web:9df32c6aaed5ad825bf17f',
    messagingSenderId: '657087009134',
    projectId: 'bybv-69690',
    authDomain: 'bybv-69690.firebaseapp.com',
    storageBucket: 'bybv-69690.firebasestorage.app',
  );
}
